name: 'Protohackers CI runner'

on: 
  pull_request:

jobs:
  test:
    name: Code testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: n8maninger/action-golang-test@v1
